"""Initial migration for Users, ScanRecord, and ML_Features models

Revision ID: 94a5b6d40d8e
Revises: 
Create Date: 2026-09-05 14:31:01.056309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94a5b6d40d8e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('scan_records',
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('url_scanned', sa.Text(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('risk_indicators', sa.Text(), nullable=True),
    sa.Column('scan_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('scan_id')
    )
    with op.batch_alter_table('scan_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_records_scan_time'), ['scan_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_records_user_id'), ['user_id'], unique=False)

    op.create_table('ml_features',
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('url_length', sa.Integer(), nullable=False),
    sa.Column('domain_entropy', sa.Float(), nullable=False),
    sa.Column('has_https', sa.Integer(), nullable=False),
    sa.Column('has_ip_address', sa.Integer(), nullable=False),
    sa.Column('dot_count', sa.Integer(), nullable=False),
    sa.Column('subdomain_count', sa.Integer(), nullable=False),
    sa.Column('special_char_count', sa.Integer(), nullable=False),
    sa.Column('redirect_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scan_records.scan_id'], ),
    sa.PrimaryKeyConstraint('feature_id')
    )
    with op.batch_alter_table('ml_features', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_features_scan_id'), ['scan_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_features', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_features_scan_id'))

    op.drop_table('ml_features')
    with op.batch_alter_table('scan_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_scan_records_scan_time'))

    op.drop_table('scan_records')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
